version: '3.1'
services:
  rsg-api:
    container_name: rsg-api
    image: springboot-postgresql
    build: ./
    ports:
    - "8080:8080"
    depends_on:
      - rsg-db
  rsg-db:
    image: postgres
    container_name: rsg-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5454:5432"