spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://rds-db:5454/rds
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
   port: 8080
   error:
     include-stacktrace: never

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000